### ISSUE TITLE
Ability to save cache even on failure

### ISSUE THREAD

**Issue by franklinkim** [magnetikonline/action-golang-cache#2]
Hi, I would need access to the cache key to be able to save the cache despite any other failures as documented here: https://github.com/actions/cache/blob/main/caching-strategies.md#saving-cache-even-if-the-build-fails

**Comment by magnetikonline** [comment]
Hey Kevin - thx for the issue 👍 

- Just a little confused from your link - what output do you want piped through, as you've linked to an example that uses `outputs.cache-hit`?
- Also this example is for `actions/cache/restore` - not `actions/cache`. I don't use (or need) the former.

Let me know - if it's just threading through an output from `actions/cache` - then that should be trivial to add in a backward compat. way.

**Comment by franklinkim** [comment]
Hey,

sorry, my bad, pasted the wrong link.
would be nice to reference the key you use in 

```
    - name: Setup Golang cache
      uses: actions/cache@v3
      with:
        path: |
          ${{ steps.golang-path.outputs.build }}
          ${{ steps.golang-path.outputs.module }}
        key: ${{ runner.os }}-golang${{ inputs.cache-key-suffix && '-' }}${{ inputs.cache-key-suffix }}-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-golang${{ inputs.cache-key-suffix && '-' }}${{ inputs.cache-key-suffix }}-
```

with sth like:

```
steps:
  - uses: actions/checkout@v3
  ...
  - name: Setup Golang with cache
    id: setup-golang
    uses: magnetikonline/action-golang-cache@v3
  ...
  - uses: actions/cache/save@v3
    if: always()
    with:
      path: path/to/dependencies
     key: ${{ steps.setup-golang.outputs.cache-key }}
```
