### ISSUE TITLE
It it working for `go build`?

### ISSUE THREAD

**Issue by Satont** [magnetikonline/action-golang-cache#5]
That seems like when i'm executing `go build `inside my action, then all dependencies re-downloaded.

Maybe it is possible to adjust some settings to caching for bypass that?

```
> twir@ cli /home/runner/work/twir/twir
> go build -ldflags="-s -w" -o .out/twir-${{ matrix.target }} ./cmd/main.go

go: downloading go.uber.org/fx v1.20.1
go: downloading github.com/getsentry/sentry-go v0.26.0
go: downloading github.com/rs/zerolog v1.31.0
go: downloading github.com/samber/slog-multi v1.0.2
go: downloading github.com/samber/slog-sentry/v2 v2.4.0
go: downloading github.com/samber/slog-zerolog/v2 v2.2.0
go: downloading github.com/alexedwards/scs/v2 v2.7.0
go: downloading github.com/redis/go-redis/v9 v9.4.0
go: downloading gorm.io/driver/postgres v1.5.4
go: downloading gorm.io/gorm v1.25.7
go: downloading github.com/mattn/go-colorable v0.1.[13](https://github.com/twirapp/twir/actions/runs/8308914608/job/22739680455#step:12:14)
go: downloading go.uber.org/dig v1.17.1
go: downloading github.com/samber/slog-common v0.15.0
go: downloading github.com/minio/minio-go/v7 v7.0.65
go: downloading github.com/goccy/go-json v0.10.2
go: downloading github.com/alexedwards/scs/goredisstore v0.0.0-20231113091[14](https://github.com/twirapp/twir/actions/runs/8308914608/job/22739680455#step:12:15)6-cef4b05350c8
go: downloading github.com/bakins/twirpotel v0.0.0-20220429133747-bfa7bdb36bf0
go: downloading github.com/nats-io/nats.go v1.33.1
go: downloading go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc v0.48.0
go: downloading google.golang.org/grpc v1.62.0
go: downloading github.com/uptrace/uptrace-go v1.21.0
go: downloading github.com/jackc/pgx/v5 v5.5.2
go: downloading github.com/mattn/go-isatty v0.0.20
go: downloading github.com/jinzhu/now v1.1.5
go: downloading github.com/dgryski/go-rendezvous v0.0.0-20200823014737-9f7001d12a5f
go: downloading github.com/guregu/null v4.0.0+incompatible
go: downloading github.com/satori/go.uuid v1.2.0
go: downloading github.com/golang/protobuf v1.5.4
go: downloading github.com/imroc/req/v3 v3.42.3
go: downloading github.com/shkh/lastfm-go v0.0.0-201912[15](https://github.com/twirapp/twir/actions/runs/8308914608/job/22739680455#step:12:16)035245-89a801c244e0
go: downloading github.com/raitonoberu/ytsearch v0.2.0
go: downloading github.com/microcosm-cc/bluemonday v1.0.26
go: downloading github.com/Masterminds/squirrel v1.5.4
go: downloading github.com/bytedance/sonic v1.10.2
go: downloading github.com/golang-jwt/jwt/v4 v4.5.0
go: downloading github.com/json-iterator/go v1.1.12
go: downloading github.com/minio/md5-simd v1.1.2
go: downloading gopkg.in/ini.v1 v1.67.0
go: downloading github.com/minio/sha256-simd v1.0.1
go: downloading github.com/nats-io/nkeys v0.4.7
go: downloading github.com/nats-io/nuid v1.0.1
go: downloading google.golang.org/genproto v0.0.0-20240123012728-ef4313101c80
go: downloading go.opentelemetry.io/contrib/instrumentation/runtime v0.46.1
go: downloading go.opentelemetry.io/otel/exporters/otlp/otlpmetric/otlpmetricgrpc v0.44.0
go: downloading go.opentelemetry.io/otel/exporters/stdout/stdouttrace v1.21.0
go: downloading go.opentelemetry.io/otel/sdk/metric v1.21.0
go: downloading github.com/jinzhu/inflection v1.0.0
go: downloading github.com/jackc/pgservicefile v0.0.0-20231201235250-de7065d80cb9
go: downloading github.com/aymerick/douceur v0.2.0
go: downloading github.com/hashicorp/go-multierror v1.1.1
go: downloading github.com/refraction-networking/utls v1.6.1
go: downloading github.com/lann/builder v0.0.0-20180802200727-47ae307949d0
go: downloading github.com/modern-go/concurrent v0.0.0-20180306012644-bacd9c7ef1dd
go: downloading github.com/modern-go/reflect2 v1.0.2
go: downloading github.com/klauspost/cpuid/v2 v2.2.6
go: downloading github.com/jackc/puddle/v2 v2.2.1
go: downloading github.com/jackc/puddle v1.3.0
go: downloading github.com/gorilla/css v1.0.1
go: downloading github.com/quic-go/quic-go v0.41.0
go: downloading github.com/hashicorp/errwrap v1.1.0
go: downloading github.com/lann/ps v0.0.0-20150810152359-62de8c46ede0
go: downloading github.com/cenkalti/backoff v2.2.1+incompatible
go: downloading github.com/grpc-ecosystem/grpc-gateway/v2 v2.18.1
go: downloading github.com/grpc-ecosystem/grpc-gateway v1.[16](https://github.com/twirapp/twir/actions/runs/8308914608/job/22739680455#step:12:17).0
go: downloading github.com/andybalholm/brotli v1.1.0
go: downloading github.com/cloudflare/circl v1.3.7
go: downloading github.com/chenzhuoyu/base64x v0.0.0-202307[17](https://github.com/twirapp/twir/actions/runs/8308914608/job/22739680455#step:12:18)1[21](https://github.com/twirapp/twir/actions/runs/8308914608/job/22739680455#step:12:22)745-[29](https://github.com/twirapp/twir/actions/runs/8308914608/job/22739680455#step:12:30)6ad89f973d
go: downloading golang.org/x/arch v0.6.0
go: downloading github.com/twitchyliquid[64](https://github.com/twirapp/twir/actions/runs/8308914608/job/22739680455#step:12:65)/golang-asm v0.15.1
go: downloading github.com/chenzhuoyu/iasm v0.9.1
```

```yaml
name: Docker v3

on:
  push:
  workflow_dispatch:

jobs:
  build-matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - api
          - bots
          - discord
          - emotes-cacher
          - eval
          - events
          - eventsub
          - integrations
          - parser
          - scheduler
          - timers
          - tokens
          - websockets
          - ytsr
    steps:
      - uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - uses: pnpm/action-setup@v3
        with:
          version: 8
          run_install: false
      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - name: Install Node.js dependencies
        run: pnpm install --frozen-lockfile

      - name: Setup Golang dependencies
        uses: magnetikonline/action-golang-cache@v5
        with:
          go-version-file: go.work

      - name: Install binaries dependencies
        run: pnpm cli deps -skip-node -skip-go

      - name: Setup turborepo cache
        uses: dtinth/setup-github-actions-caching-for-turbo@v1
      - name: Build libraries
        run: pnpm cli build libs

      - name: Build application
        run: pnpm cli build app ${{ matrix.target }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
#      - name: Login to Docker Hub
#        uses: docker/login-action@v3
#        with:
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./apps/${{ matrix.target }}/Dockerfile
          push: false
          tags: twir/${{ matrix.target }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
```
